Repository IgniteUI/igniteui-webcomponents, pull requests merged in 2024-10, with the labels that each got.

#1409 refactor(dropdown): update items sizes and paddings
  src/components/dropdown/themes/dropdown-item.base.scss
  src/components/dropdown/themes/header.ts
  src/components/dropdown/themes/shared/dropdown.common.scss
  src/components/dropdown/themes/shared/dropdown.fluent.scss
  src/components/dropdown/themes/shared/dropdown.indigo.scss
  src/components/dropdown/themes/shared/dropdown.material.scss
  src/components/dropdown/themes/shared/header/dropdown-header.common.scss
  src/components/dropdown/themes/shared/header/dropdown-header.fluent.scss
  src/components/dropdown/themes/shared/header/dropdown-header.indigo.scss
  src/components/dropdown/themes/shared/item/dropdown-item.common.scss
  src/components/dropdown/themes/shared/item/dropdown-item.fluent.scss
  src/components/dropdown/themes/shared/item/dropdown-item.indigo.scss
  stories/dropdown.stories.ts
Labels: :white_check_mark: status: verified, themes, design: verified, drop-down, combo

#1408 Themes: Indigo updates for the Chip and Tabs
  package-lock.json
  package.json
  src/components/chip/themes/chip.base.scss
  src/components/chip/themes/dark/chip.indigo.scss
  src/components/chip/themes/light/chip.indigo.scss
  src/components/chip/themes/shared/chip.common.scss
  src/components/chip/themes/shared/chip.fluent.scss
  src/components/chip/themes/shared/chip.indigo.scss
  src/components/icon/icon-references.ts
  src/components/tabs/tabs.ts
  src/components/tabs/themes/dark/tab.bootstrap.scss
  src/components/tabs/themes/dark/tab.fluent.scss
  src/components/tabs/themes/dark/tab.indigo.scss
  src/components/tabs/themes/dark/tab.material.scss
  src/components/tabs/themes/light/tab.bootstrap.scss
  src/components/tabs/themes/light/tab.fluent.scss
  src/components/tabs/themes/light/tab.indigo.scss
  src/components/tabs/themes/light/tab.material.scss
  src/components/tabs/themes/shared/tab/tab.indigo.scss
  src/components/tabs/themes/shared/tabs/tabs.indigo.scss
  src/components/tabs/themes/tab-themes.ts
  src/components/tabs/themes/tab.base.scss
  src/components/tabs/themes/tabs-themes.ts
  src/components/tabs/themes/tabs.base.scss
Labels: :white_check_mark: status: verified, themes, chip, design: verified, indigo-theme, tab

#1404 refactor(icon-rigistry): update input expand/collapse icons
  src/components/icon/icon-references.ts
  stories/date-time-input.stories.ts
Labels: icon, design: verified, select, combo

#1416 feat(chip): update slotted items size
  src/components/chip/themes/shared/chip.common.scss
Labels: :white_check_mark: status: verified, chip

#1415 fix(expansion-panel): text styles and typography
  src/components/expansion-panel/themes/expansion-panel.base.scss
  src/components/expansion-panel/themes/shared/expansion-panel.bootstrap.scss
  src/components/expansion-panel/themes/shared/expansion-panel.common.scss
  src/components/expansion-panel/themes/shared/expansion-panel.fluent.scss
Labels: :white_check_mark: status: verified, themes, expansion-panel, typography, design: verified

#1399 refactor(badge): update font-size and padding
  src/components/badge/themes/badge.base.scss
  src/components/badge/themes/shared/badge.common.scss
Labels: :white_check_mark: status: verified, themes, badge, refactoring

#1418 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1414 fix(card): update card paddings to match UI kits
  src/components/card/themes/shared/content/card.content.bootstrap.scss
  src/components/card/themes/shared/header/card.header.fluent.scss
Labels: :white_check_mark: status: verified, card, design: in-validation

#1419 fix(icon-service): Dispose of broadcast channel on pagehide
  src/components/icon/icon-state.broadcast.ts
Labels: icon

#1420 feat(tile-manager): implement base resizing logic
  src/components/tile-manager/themes/tile-manager.base.scss
  src/components/tile-manager/themes/tile.base.scss
  src/components/tile-manager/tile.ts
Labels: DO-NOT-MERGE

#1421 tests: Refactor validation container integration scenarios
  src/components/checkbox/checkbox.spec.ts
  src/components/combo/combo.spec.ts
  src/components/common/utils.spec.ts
  src/components/date-picker/date-picker.spec.ts
  src/components/date-time-input/date-time-input.spec.ts
  src/components/input/input.spec.ts
  src/components/mask-input/mask-input.spec.ts
  src/components/radio/radio.spec.ts
  src/components/select/select.spec.ts
  src/components/textarea/textarea.spec.ts
Labels: squash-merge, refactoring, tests

#1424 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1427 fix(switch, checkbox): click event fires more than once
  src/components/checkbox/checkbox-base.ts
  src/components/checkbox/checkbox.spec.ts
  src/components/checkbox/checkbox.ts
Labels: :white_check_mark: status: verified, switch, checkbox

#1428 fix(radio): Click event is fired more than once
  CHANGELOG.md
  src/components/radio/radio.spec.ts
  src/components/radio/radio.ts
Labels: radio

#1388 feat(theming): migrate palettes to relative colors
  package-lock.json
  package.json
Labels: :white_check_mark: status: verified, themes

#1430 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1431 fix(ripple): remove hsl prefix from the default color
  src/components/ripple/ripple.ts
Labels: :white_check_mark: status: verified, ripple

#1432 stories: colors should work with relative palettes
  stories/icon.stories.ts
  stories/select.stories.ts
Labels: :book: storybook

#1422 Export component event maps
  .vscode/cspell.json
  package.json
  scripts/_package.json
  src/components/calendar/calendar.ts
  src/components/calendar/days-view/days-view.ts
  src/components/calendar/months-view/months-view.ts
  src/components/calendar/types.ts
  src/components/calendar/years-view/years-view.ts
  src/components/checkbox/checkbox-base.ts
  src/components/chip/chip.ts
  src/components/combo/combo.ts
  src/components/combo/types.ts
  src/components/common/controllers/gestures.ts
  src/components/date-picker/date-picker.ts
  src/components/date-time-input/date-time-input.ts
  src/components/dialog/dialog.ts
  src/components/dropdown/dropdown.ts
  src/components/input/input-base.ts
  src/components/radio/radio.ts
  src/components/rating/rating.ts
  src/components/ripple/ripple.spec.ts
  src/components/select/select.ts
  src/components/slider/range-slider.ts
  src/components/slider/slider.ts
  src/components/snackbar/snackbar.ts
  src/components/stepper/stepper.common.ts
  src/components/stepper/stepper.ts
  src/components/tabs/tabs.ts
  src/components/textarea/textarea.ts
  src/components/tree/tree.common.ts
  src/components/tree/tree.ts
  src/components/validation-container/validation-container.ts
  src/index.ts
  stories/tree.stories.ts
  tsconfig.json
Labels: squash-merge

#1436 chore(storybook): Use the new internal import path
  stories/accordion.stories.ts
  stories/avatar.stories.ts
  stories/badge.stories.ts
  stories/banner.stories.ts
  stories/button-group.stories.ts
  stories/button.stories.ts
  stories/calendar.stories.ts
  stories/card.stories.ts
  stories/carousel.stories.ts
  stories/checkbox.stories.ts
  stories/chip.stories.ts
  stories/circular-progress.stories.ts
  stories/combo.stories.ts
  stories/date-time-input.stories.ts
  stories/datepicker.stories.ts
  stories/dialog.stories.ts
  stories/divider.stories.ts
  stories/dropdown.stories.ts
  stories/expansion-panel.stories.ts
  stories/icon-button.stories.ts
  stories/icon.stories.ts
  stories/input.stories.ts
  stories/linear-progress.stories.ts
  stories/list.stories.ts
  stories/mask-input.stories.ts
  stories/nav-drawer.stories.ts
  stories/navbar.stories.ts
  stories/radio-group.stories.ts
  stories/radio.stories.ts
  stories/range-slider.stories.ts
  stories/rating.stories.ts
  stories/ripple.stories.ts
  stories/select.stories.ts
  stories/slider.stories.ts
  stories/snackbar.stories.ts
  stories/stepper.stories.ts
  stories/story.ts
  stories/switch.stories.ts
  stories/tabs.stories.ts
  stories/textarea.stories.ts
  stories/toast.stories.ts
  stories/tree.stories.ts
Labels: refactoring, :book: storybook

#1437 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1438 chore(storybook): Sourcemaps and files for SB cache
  package.json
Labels: :book: storybook

#1435 docs: Updated CHANGELOG
  CHANGELOG.md
Labels: documentation

#1440 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1444 fix(calendar): Cannot select dates before UNIX epoch
  CHANGELOG.md
  src/components/calendar/calendar.interaction.spec.ts
  src/components/calendar/days-view/days-view.ts
  src/components/calendar/months-view/months-view.ts
  src/components/calendar/years-view/years-view.ts
Labels: :white_check_mark: status: verified, calendar, date-picker

#1445 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1446 build(deps): Updated theming package dependency
  package-lock.json
  package.json
Labels: dependencies

#1447 refactor: Use an EventTarget derived emitter for theme changes
  src/theming/theming-controller.ts
  src/theming/theming-event.ts
Labels: themes, refactoring

#1449 refactor: Themes emitter SSR initialization
  src/theming/theming-event.ts
Labels: themes, refactoring

#1452 docs: Updated CHANGELOG release notes
  CHANGELOG.md
Labels: changelog

#1453 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies
