Repository IgniteUI/igniteui-webcomponents, pull requests merged in 2024-09, with the labels that each got.

#1372 build: Updated dependencies and browserslist config
  .browserslistrc
  .stylelintrc.json
  package-lock.json
  package.json
Labels: dependencies

#1376 build: Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1378 build: Bumped to latest TS version
  package-lock.json
  package.json
Labels: dependencies

#1380 build: Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1358 refactor: Key bindings controller
  src/components/accordion/accordion.ts
  src/components/common/controllers/key-bindings.spec.ts
  src/components/common/controllers/key-bindings.ts
Labels: squash-merge, refactoring, accordion

#1382 build: Bumped dependencies
  biome.json
  package-lock.json
  package.json
  stories/calendar.stories.ts
  stories/datepicker.stories.ts
  stories/tree.stories.ts
Labels: dependencies

#1381 refactor(rating): Skip default symbols when there are projected ones
  src/components/rating/rating.spec.ts
  src/components/rating/rating.ts
Labels: refactoring, rating

#1384 build: Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1387 build: Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1390 build: Refactor styles and themes build pipeline
  .storybook/preview.ts
  scripts/build-styles.mjs
  scripts/build.mjs
  scripts/sass.mjs
Labels: themes, refactoring

#1329 feat(calendar): Expose header-date slot and align header UI to the Angular version
  src/components/calendar/calendar-rendering.spec.ts
  src/components/calendar/calendar.ts
  src/components/calendar/helpers.spec.ts
  src/components/date-picker/date-picker.spec.ts
  src/components/date-picker/date-picker.ts
Labels: :boom: status: in-test, calendar, date-picker

#1363 input-group - update label typography
  src/components/input/themes/input.base.scss
  src/components/input/themes/shared/input.bootstrap.scss
  src/components/input/themes/shared/input.fluent.scss
  src/components/input/themes/shared/input.indigo.scss
  src/components/input/themes/shared/input.material.scss
Labels: :white_check_mark: status: verified, input

#1337 Themes: Update Indigo Calendar, Select, and Combo
  package-lock.json
  package.json
  src/components/calendar/themes/shared/bootstrap/days-view.bootstrap.scss
  src/components/calendar/themes/shared/bootstrap/year-month-view.bootstrap.scss
  src/components/calendar/themes/shared/fluent/days-view.fluent.scss
  src/components/calendar/themes/shared/fluent/year-month-view.fluent.scss
  src/components/calendar/themes/shared/indigo/days-view.indigo.scss
  src/components/calendar/themes/shared/indigo/year-month-view.indigo.scss
  src/components/calendar/themes/shared/material/days-view.material.scss
  src/components/calendar/themes/shared/material/year-month-view.material.scss
  src/components/checkbox/checkbox-base.ts
  src/components/combo/themes/combo.base.scss
  src/components/combo/themes/shared/combo.bootstrap.scss
  src/components/combo/themes/shared/combo.fluent.scss
  src/components/combo/themes/shared/combo.indigo.scss
  src/components/combo/themes/shared/combo.material.scss
  src/components/select/themes/dark/select.bootstrap.scss
  src/components/select/themes/dark/select.fluent.scss
  src/components/select/themes/dark/select.indigo.scss
  src/components/select/themes/dark/select.material.scss
  src/components/select/themes/light/select.bootstrap.scss
  src/components/select/themes/light/select.fluent.scss
  src/components/select/themes/light/select.indigo.scss
  src/components/select/themes/light/select.material.scss
  src/components/select/themes/shared/select.common.scss
  src/components/select/themes/shared/select.fluent.scss
  src/components/select/themes/shared/select.indigo.scss
  src/components/select/themes/shared/select.material.scss
  stories/select.stories.ts
Labels: :white_check_mark: status: verified, themes, design: verified, indigo-theme

#1396 build: Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1394 refactor(navdrawer): use min-width in the mini variant
  src/components/nav-drawer/themes/container.base.scss
Labels: :x: status: awaiting-test, nav-drawer

#1398 docs: Fixed broken README links
  README.md
Labels: documentation

#1389 refactor(form-mixin): Refactor form components for native behavior alignment
  src/components/checkbox/checkbox-base.ts
  src/components/checkbox/checkbox.spec.ts
  src/components/checkbox/switch.spec.ts
  src/components/combo/combo.spec.ts
  src/components/combo/combo.ts
  src/components/common/mixins/form-associated-required.ts
  src/components/common/mixins/form-associated.ts
  src/components/common/mixins/forms/associated-required.ts
  src/components/common/mixins/forms/associated.ts
  src/components/common/mixins/forms/types.ts
  src/components/common/utils.spec.ts
  src/components/date-picker/date-picker.spec.ts
  src/components/date-picker/date-picker.ts
  src/components/date-time-input/date-time-input.spec.ts
  src/components/date-time-input/date-time-input.ts
  src/components/input/input-base.ts
  src/components/input/input.spec.ts
  src/components/input/input.ts
  src/components/mask-input/mask-input.spec.ts
  src/components/mask-input/mask-input.ts
  src/components/radio-group/radio-group.ts
  src/components/radio/radio.spec.ts
  src/components/radio/radio.ts
  src/components/rating/rating.spec.ts
  src/components/rating/rating.ts
  src/components/select/select.spec.ts
  src/components/select/select.ts
  src/components/slider/slider.spec.ts
  src/components/slider/slider.ts
  src/components/textarea/textarea.spec.ts
  src/components/textarea/textarea.ts
  stories/checkbox.stories.ts
  stories/combo.stories.ts
  stories/date-time-input.stories.ts
  stories/input.stories.ts
  stories/mask-input.stories.ts
  stories/radio.stories.ts
  stories/rating.stories.ts
  stories/select.stories.ts
  stories/slider.stories.ts
  stories/switch.stories.ts
  stories/textarea.stories.ts
Labels: :white_check_mark: status: verified, squash-merge, forms

#1403 docs: Updated CHANGELOG
  CHANGELOG.md
Labels: documentation

#1275 Add Carousel component
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/_package.json
  src/components/carousel/animations.ts
  src/components/carousel/carousel-indicator-container.spec.ts
  src/components/carousel/carousel-indicator-container.ts
  src/components/carousel/carousel-indicator.ts
  src/components/carousel/carousel-slide.ts
  src/components/carousel/carousel.spec.ts
  src/components/carousel/carousel.ts
  src/components/carousel/context.ts
  src/components/carousel/themes/carousel-indicator-container.base.scss
  src/components/carousel/themes/carousel-indicator.base.scss
  src/components/carousel/themes/carousel-slide.base.scss
  src/components/carousel/themes/carousel.base.scss
  src/components/carousel/themes/container.ts
  src/components/carousel/themes/dark/_themes.scss
  src/components/carousel/themes/dark/carousel.bootstrap.scss
  src/components/carousel/themes/dark/carousel.fluent.scss
  src/components/carousel/themes/dark/carousel.indigo.scss
  src/components/carousel/themes/dark/carousel.material.scss
  src/components/carousel/themes/dark/carousel.shared.scss
  src/components/carousel/themes/indicator-container.ts
  src/components/carousel/themes/light/_themes.scss
  src/components/carousel/themes/light/carousel.bootstrap.scss
  src/components/carousel/themes/light/carousel.fluent.scss
  src/components/carousel/themes/light/carousel.indigo.scss
  src/components/carousel/themes/light/carousel.material.scss
  src/components/carousel/themes/light/carousel.shared.scss
  src/components/carousel/themes/shared/carousel.bootstrap.scss
  src/components/carousel/themes/shared/carousel.common.scss
  src/components/carousel/themes/shared/carousel.fluent.scss
  src/components/carousel/themes/shared/carousel.indigo.scss
  src/components/carousel/themes/shared/indicator-container/indicator-container.bootstrap.scss
  src/components/carousel/themes/shared/indicator-container/indicator-container.common.scss
  src/components/carousel/themes/shared/indicator-container/indicator-container.fluent.scss
  src/components/carousel/themes/shared/indicator-container/indicator-container.indigo.scss
  src/components/common/controllers/gestures.spec.ts
  src/components/common/controllers/gestures.ts
  src/components/common/definitions/defineAllComponents.ts
  src/components/common/utils.spec.ts
  src/components/icon/icon-references.ts
  src/components/icon/internal-icons-lib.ts
  src/index.ts
  stories/carousel.stories.ts
Labels: :white_check_mark: status: verified, DO-NOT-MERGE, design: verified, carousel

#1395 feat(tabs): update theme according to new Indigo design
  src/components/icon/icon-references.ts
  src/components/tabs/tabs.ts
  src/components/tabs/themes/dark/tab.bootstrap.scss
  src/components/tabs/themes/dark/tab.fluent.scss
  src/components/tabs/themes/dark/tab.indigo.scss
  src/components/tabs/themes/dark/tab.material.scss
  src/components/tabs/themes/light/tab.bootstrap.scss
  src/components/tabs/themes/light/tab.fluent.scss
  src/components/tabs/themes/light/tab.indigo.scss
  src/components/tabs/themes/light/tab.material.scss
  src/components/tabs/themes/shared/tab/tab.indigo.scss
  src/components/tabs/themes/shared/tabs/tabs.indigo.scss
  src/components/tabs/themes/tab-themes.ts
  src/components/tabs/themes/tab.base.scss
  src/components/tabs/themes/tabs-themes.ts
  src/components/tabs/themes/tabs.base.scss
Labels: :x: status: awaiting-test, design: awaiting-validation, indigo-theme, tab
