Repository IgniteUI/igniteui-webcomponents, pull requests merged in 2025-06, with the labels that each got.

#1724 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1728 fix(combo): use hardcoded color for case-icon in all themes
  src/components/combo/themes/combo.base.scss
Labels: :white_check_mark: status: verified, combo, styling

#1684 refactor: Keyboard focus ring controller
  src/components/button-group/toggle-button.ts
  src/components/button/button-base.ts
  src/components/carousel/carousel-indicator-container.spec.ts
  src/components/carousel/carousel-indicator-container.ts
  src/components/carousel/carousel.ts
  src/components/checkbox/checkbox-base.ts
  src/components/checkbox/checkbox.ts
  src/components/checkbox/switch.ts
  src/components/common/controllers/focus-ring.spec.ts
  src/components/common/controllers/focus-ring.ts
  src/components/common/mixins/option.ts
  src/components/radio/radio.ts
Labels: refactoring

#1720 fix(calendar): Clamp date arithmetic rollovers
  CHANGELOG.md
  src/components/calendar/model.spec.ts
  src/components/calendar/model.ts
  src/components/date-picker/date-picker.spec.ts
Labels: :white_check_mark: status: verified, calendar, date-picker, date-range-picker

#1736 refactor: Keybinding controller
  src/components/common/controllers/key-bindings.ts
  src/components/common/util.ts
  src/components/date-time-input/date-time-input.ts
  src/components/dropdown/dropdown.ts
  src/components/radio/radio.ts
Labels: refactoring

#1713 fix(file-group): misalignment in material variant
  src/components/file-input/file-input.ts
  src/components/file-input/themes/file-input.base.scss
Labels: :white_check_mark: status: verified, input, styling

#1740 refactor(tooltip): Align API and behavior to Angular tooltip
  CHANGELOG.md
  src/components/tooltip/tooltip.spec.ts
  src/components/tooltip/tooltip.ts
Labels: changelog, tooltip

#1741 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1743 fix(date-range-picker): Consistent focus on open and active day view
  src/components/calendar/calendar.ts
  src/components/calendar/days-view/days-view.ts
  src/components/calendar/months-view/months-view.ts
  src/components/calendar/years-view/years-view.ts
  src/components/date-range-picker/date-range-picker.ts
Labels: enhancement, :white_check_mark: status: verified, date-range-picker

#1745 chore: Updated CHANGELOG, stories and stories metadata
  CHANGELOG.md
  scripts/_package.json
  stories/badge.stories.ts
  stories/input.stories.ts
  stories/tooltip.stories.ts
Labels: :book: storybook, changelog

#1748 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1750 build(deps): Bumped dependencies
  biome.json
  package-lock.json
  package.json
  src/components/common/util.ts
  src/components/common/utils.spec.ts
Labels: dependencies

#1754 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1756 refactor: Mutation observer controller
  src/components/button-group/button-group.ts
  src/components/carousel/carousel.ts
  src/components/common/controllers/mutation-observer.ts
  src/components/select/select-group.ts
  src/components/tabs/tabs.ts
Labels: refactoring

#1757 refactor: Moved constructor event bindings to SSR safe API
  src/components/accordion/accordion.ts
  src/components/calendar/days-view/days-view.ts
  src/components/calendar/months-view/months-view.ts
  src/components/calendar/years-view/years-view.ts
  src/components/carousel/carousel.ts
  src/components/combo/combo.ts
  src/components/common/mixins/forms/associated.ts
  src/components/common/util.ts
  src/components/date-picker/date-picker.ts
  src/components/date-range-picker/date-range-picker.ts
  src/components/focus-trap/focus-trap.ts
  src/components/ripple/ripple.ts
  src/components/select/select.ts
  src/components/slider/slider-base.ts
  src/components/textarea/textarea.ts
  src/components/tree/tree-item.ts
  src/components/tree/tree.ts
Labels: refactoring, SSR

#1753 fix(input, file-input): refine label positioning in material theme
  src/components/file-input/themes/shared/file-input.material.scss
  src/components/input/themes/shared/input.material.scss
Labels: :white_check_mark: status: verified, input, text area, file-input

#1755 fix(dropdown): icon size in bootstrap theme
  src/components/dropdown/themes/item.ts
  src/components/dropdown/themes/shared/item/dropdown-item.bootstrap.scss
Labels: :white_check_mark: status: verified, bootstrap-theme, drop-down

#1766 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies
