Repository IgniteUI/igniteui-webcomponents, pull requests merged in 2025-05, with the labels that each got.

#1681 build(deps): Bumped dependencies
  package-lock.json
  package.json
Labels: dependencies

#1685 build(deps): Bumped to latest Storybook rc
  package-lock.json
  package.json
  src/components/tabs/themes/tab.base.scss
Labels: dependencies

#1670 refactor(textarea): Use resize observer controller
  src/components/common/controllers/resize-observer.ts
  src/components/tabs/tabs.ts
  src/components/textarea/textarea.spec.ts
  src/components/textarea/textarea.ts
Labels: squash-merge, refactoring, text area

#1691 docs: Update issue template and README links
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
Labels: documentation

#1700 build(deps): Bumped dependencies
  package-lock.json
  package.json
  vite.config.ts
Labels: dependencies

#1692 refactor(date-picker): Interaction behavior in readonly mode
  src/components/calendar/helpers.spec.ts
  src/components/date-picker/date-picker-form.spec.ts
  src/components/date-picker/date-picker.spec.ts
  src/components/date-picker/date-picker.ts
Labels: refactoring, date-picker

#1702 build(deps): Bumped to latest Storybook
  package-lock.json
  package.json
Labels: dependencies

#1690 fix(textarea): Dynamic prefix/suffix slot content state
  CHANGELOG.md
  src/components/textarea/textarea.spec.ts
  src/components/textarea/textarea.ts
Labels: :white_check_mark: status: verified, squash-merge, text area

#1705 fix(tabs): Internal DOM reference checks in observers
  src/components/tabs/tab-dom.ts
  src/components/tabs/tabs.spec.ts
Labels: tab

#1709 Update ROADMAP.md
  ROADMAP.md
Labels: documentation

#1689 refactor: Simplify iterNodes implementation
  src/components/common/mixins/combo-box.ts
  src/components/common/util.ts
  src/components/radio/utils.ts
Labels: squash-merge, refactoring

#1714 build(deps): Bumped Storybook to latest version
  package-lock.json
  package.json
Labels: dependencies
